### ISSUE TITLE
Issues with non-starting persons

### ISSUE THREAD

**Issue by schwepmo** [lcodeca/SUMOActivityGen#10]
Hey Lara,
I'm trying to use your scripts to generate a small scenario of part of Berlin. Overall it works really well but I'm facing some issues. 
* first of a lot of pedestrians are not starting their route-definitions, because they can't mount their bikes (see below). I believe this is because bike and person are not on the same position of an edge. Do you have any hints as to how to solve this problem.
![image](https://user-images.githubusercontent.com/39306374/83760158-d64cdc80-a674-11ea-957c-2ead286aee7b.png)
* the second problem I'm facing is related to parking areas. As you can see below the generated parking areas are very small and sparse. And usually it is also possible to park on the side of the street, is there are way to manually broaden parking areas?
![image](https://user-images.githubusercontent.com/39306374/83760435-39d70a00-a675-11ea-9487-6c39edac2c91.png)

Thanks in advance!

**Comment by lcodeca** [comment]
Hi, 
for me to understand what's going on with people and bikes, I need to debug the scenario that you are using.
On the parking, netconvert is taking care of the on-street parking and my scripts are dealing with the other cases. The area that you are showing me is not on the road; it can be underground parking or parking for a supermarket, something like that. Given the lack of info for that specific one, all the parking spaces are crammed together, but it's only a matter of visualization, and it does not change sumo behavior. If you don't see on-street parking, it may be that the definition in OSM malformed and netconvert cannot deal with it. Anyway, you can change everything in the automagically generated XML files. You need to check in the sumo config which parking file is loaded, and change it (see [https://sumo.dlr.de/docs/Simulation/ParkingArea.html](https://sumo.dlr.de/docs/Simulation/ParkingArea.html)).

**Comment by schwepmo** [comment]
Hey,
thanks for the quick answer. Upon further inspection, the parking issue is indeed just a matter of visualization. However the bike situation remains. What's weird is, that some persons are able to successfully ride their bikes, while other just stay next to it for the whole simulation. I've attached the osm and the configurations that were used for generation a swell as the generated scenario. 
Maybe that helps to make sense of it.
Thanks again for your help!
[bundesplatz_scenario.zip](https://github.com/lcodeca/SUMOActivityGen/files/4740139/bundesplatz_scenario.zip)

**Comment by schwepmo** [comment]
Hey again,
I think I figured it out by myself. It is as well a matter of visualization. The persons 'waiting' to mount their bikes are actually doing one of the defined activities (`<stop>`-definitions) and just parked their bikes on the street. I falsely assumed they didn't start their routes because I didn't look at the times.
Thanks again for your help, and sorry for my kinda stupid questions. I'll close the issue.
