### ISSUE TITLE
Compatibility with SUMO 1.5/1.6

### ISSUE THREAD

**Issue by abrac** [lcodeca/SUMOActivityGen#11]
Firstly, thank you for this amazing project! 

What is the current state of compatibility with SUMO 1.5 and 1.6? I require Demand-Responsive Transport in my simulation (i.e. *Taxis*) which is not available in v1.4.

**Comment by lcodeca** [comment]
I use the development version of sumo, so there should be no issues with versions 1.5 or 1.6
I'm currently working os supporting taxis in the generation but it's a work in progress, and being this a side project, I don't know when I can actually make it happen. I have a private branch where I have already extracted the taxi stands from OSM, but they are not yet part of the activity generation. If you are interested in contributing to it, I can make time to clean what I have already done and push it.

**Comment by abrac** [comment]
Hi Lara. That is good news. I am keen, but need to familiarise myself a bit more with your source code. I'll open a new issue regarding the taxis if that's fine.
