### ISSUE TITLE
Problems for generateTAZBuildingsFromOSM.py

### ISSUE THREAD

**Issue by Shiyunyang-seu** [lcodeca/SUMOActivityGen#15]
Hi, when the information of building is missing（or the input is not osm）, but I have terrain attribute data, and also I created the taz.xml , how can I generate TAZ_ weight.scv (do I just need to calculate the area of each TAZ by shapes, what does "#Node" stand for? Can it be calculated? Is it an essential element in creating an OD matrix? ).
Thanks in advance!

**Comment by lcodeca** [comment]
Hello, if the input is not OSM my tool requires a lot of changes.
The weight file is generated here https://github.com/lcodeca/SUMOActivityGen/blob/0af8cb8c52f78a72dc819d12c814eba8cbc509f8/generateTAZBuildingsFromOSM.py#L519 and the #Node is the number of OSM nodes contained in the area. 
The area is computed from the TAZ with https://github.com/lcodeca/SUMOActivityGen/blob/0af8cb8c52f78a72dc819d12c814eba8cbc509f8/generateTAZBuildingsFromOSM.py#L255 
The OD generation is based on "how many things" are in the TAZ and how big is it. So yeah, it's important. Nonetheless, it's just a heuristic, and to have realistic results, you should build your own OD based on statistical info on the location you are modeling.

**Comment by Shiyunyang-seu** [comment]
Thank you so much for your answer. I have studied the relevant code and there are several questions: 
1. When creating TAZ and storing building information, the information related to landuse is not stored. Can I understand that landuse is not considered in the generated OD matrix.
2. When creating the OD matrix, only the input density and area are used. Can nodes be ignored directly?
3. After inputting the default JSON file and OD matrix, how is the specific activity-based travel plan generated(using activitygen.py ） it is difficult to understand the algorithm logic of this part(How to define home location and working location without using landuse before).
Thanks in advance!

**Comment by lcodeca** [comment]
1) the land-use is not always available in OSM so it's not considered even if present.
2) the nodes are used during the activity generation as a metric for the attractiveness of an area.
3) https://github.com/lcodeca/SUMOActivityGen/blob/master/docs/SUMOActivityGen.md#metodology
