### ISSUE TITLE
Improving documentation.

### ISSUE THREAD

**Issue by lcodeca** [lcodeca/SUMOActivityGen#20]

**Comment by abrac** [comment]
Hi Lara, one of the first things that confused me when I first read the documentation was that there was no direction as to which file I should start reading first. I'm assuming [HOWTO.md](https://github.com/lcodeca/SUMOActivityGen/blob/master/docs/HOWTO.md) is supposed to act as a table of contents / index? 

If that is the case, I have two recommendations:

1. perhaps HOWTO.md should be renamed to something like "index.md" and linked to in [Readme.md (L21)](https://github.com/lcodeca/SUMOActivityGen/blame/master/README.md#L21).
2. perhaps the *optional parameters* section should be removed in [HOWTO.md (L23-L47)](https://github.com/lcodeca/SUMOActivityGen/blame/master/docs/HOWTO.md#L23-L47) as it is duplicated in [ScenarioGenerator.md](https://github.com/lcodeca/SUMOActivityGen/blame/master/docs/ScenarioGenerator.md#L9-L28)

I am making these changes to my fork and will make a pull request shortly to let you know what I mean.
