### ISSUE TITLE
Problem with running the scenarioFromOSM.py

### ISSUE THREAD

**Issue by aminissn** [lcodeca/SUMOActivityGen#23]
I tried to run a quick example using scenarioFromOSM.py but I got the following error:
TypeError: namedtuple() got an unexpected keyword argument 'defaults'
It refers to line 77 of activitygen. Is there any additional argument needed, other than providing an osm input file? Below is the command I used:
python ~/sumo-1.7.0/tools/contributed/saga/scenarioFromOSM.py --osm ./munich-200429.osm --out ./saga_output/
I am using Anaconda Python3.6 environment and SUMO-1.7.

Thanks
Sasan

**Comment by lcodeca** [comment]
I think is a difference between Python 3.6 and the one I use (Python 3.7).

**Comment by aminissn** [comment]
you are right. I tested it on Python3.8 and it works. Only need to set SUMO_TOOLS in the environment variables i.e. export SUMO_TOOLS="$SUMO_HOME/tools"

**Comment by lcodeca** [comment]
I removed the SUMO_TOOLS requirement.
