### ISSUE TITLE
Error with pedestrians while calling SUMO

### ISSUE THREAD

**Issue by anjackq** [lcodeca/SUMOActivityGen#28]
Hi,

I have successfully generated all files, and am ready to launch the SUMO. However, I got the error report from the sumo as follows:

```
Launch sumo. 
Loading configuration ... done. 
Loading net-file from 'osm.net.xml' ... done (798ms). 
Loading additional-files from 'osm_polygons.add.xml' ... done (145ms). 
Loading additional-files from 'osm_stops.add.xml' ... done (11ms). 
Loading additional-files from 'osm_complete_parking_areas.add.xml' ... done (10ms). 
Loading additional-files from 'osm_parking_rerouters.add.xml' ... done (7ms). 
Loading additional-files from 'basic.vType.xml' ... done (1ms). 
Loading done. 
Error: value 'person' not in enumeration 
 In file 'osm_activitygen..merged.rou.xml' 
 At line/column 9/83.
```

**Comment by lcodeca** [comment]
What system are you using?
What SUMO version are you using?
What SAGA version are you using? (master? sumo/tools?)
I have never seen that error, I need to check your files in order to try to understand what's going on.

**Comment by anjackq** [comment]
> What system are you using?
> What SUMO version are you using?
> What SAGA version are you using? (master? sumo/tools?)
> I have never seen that error, I need to check your files in order to try to understand what's going on.

Hi Icodeca,

I'm using the `win10` platform
SUMO version is `1.4.0`
For SAFA, I clone from the master on GitHub, however, I copied the folder` "defaults" `from somo/tools/saga to the SUMOActivityGen-master. Since I got errors while running with the --local-default.
Therefore, the `defaults` folder contains:

defaults
- activitygen.json (from somo/tools)
- basic.vType.xml (from somo/tools)
- default-gui.xml (missing file, and downloaded from net)
- duarouter.sumocfg (from somo/tools)
- osm.netccfg (from somo/tools)
- os.sumocfg (from somo/tools)

Is that, the SUMO on my computer doesn't support the pedestrian model?

**Comment by lcodeca** [comment]
As you can see in the README (https://github.com/lcodeca/SUMOActivityGen#due-to-some-changes-in-the-sumo-development-version-of-the-traci-apis-the-master-branch-may-not-compatible-with-sumo-140), SUMO 1.4.0 is not supported anymore. 
SAGA is meant to be used with the latest version of sumo, I'm trying to keep up with the latest features..

**Comment by anjackq** [comment]
> As you can see in the README (https://github.com/lcodeca/SUMOActivityGen#due-to-some-changes-in-the-sumo-development-version-of-the-traci-apis-the-master-branch-may-not-compatible-with-sumo-140), SUMO 1.4.0 is not supported anymore.
> SAGA is meant to be used with the latest version of sumo, I'm trying to keep up with the latest features..

Hi lcodeca,

after I reinstalled SUMO 1.8.0, it worked. Thanks for your reply.

BR,
Anjie
