### ISSUE TITLE
Issues with bikes using bike paths

### ISSUE THREAD

**Issue by DANIOM97** [lcodeca/SUMOActivityGen#29]
Hi!
I was wonder if maybe you can help me. I have issues with the bikes, during the simulation it takes the driving lanes rather the bike paths. How can I configure the bike path to be available and the bikes take it?

Thanks!

Daniela

**Comment by lcodeca** [comment]
Hi, I suppose you mean bicycles and not motorbikes.
If your street allows them, they'll consider it a possible route. 
You need to check the permissions on your edges.
