### ISSUE TITLE
 Administrative boundaries broken in osm

### ISSUE THREAD

**Issue by Shiyunyang-seu** [lcodeca/SUMOActivityGen#4]
Hi, I want to know if I can use the defined net.xml and additional.xml (bus stop...) to replace the input OSM file. Because I have run most of the 10 steps of activitygen and made optimization and modification to the file before, I hope to use the modified file to replace the input. I don't know if it is feasible.
[suzhou_gucheng.zip](https://github.com/lcodeca/SUMOActivityGen/files/4501001/suzhou_gucheng.zip)

**Comment by lcodeca** [comment]
All the steps are built on stand-alone components. 
No, you cannot run the generator starting from something else than an OSM file. 
The idea of SAGA is to generate the default files for you. 
Afterward, you can change them and re-compose your scenario. 
You can do it by hand launching only the scripts you are interested in, or you can use the `--from-step` option to regenerate sequentially the steps after your change.

**Comment by Shiyunyang-seu** [comment]
Thank you for your reply. I have completed acitivitygen by changing steps, replacing files, etc., but there are still some problems: 
1. There are two kinds of errors in activity creation: critical: "generate mode" Traci from "['All ']" to "['All']" with "public" generated 10 errors, Trip generation aborted..; Warning: "generate ﹐ mode ﹐ Traci generated an inconsistent plan.
2. The number of parking areas is too few.
3. I can't see the trip of activitygen.merged.rou.xml in sumo GUI. And almost all the vehicles in the simulation have a warning that can not be allowed to stop on the lane. I don't know whether it is related to the previous parking area creation. How to solve the above problems? Thanks a lot
[target_directory.zip](https://github.com/lcodeca/SUMOActivityGen/files/4502412/target_directory.zip)
.

**Comment by lcodeca** [comment]
SAGA uses netconvert so is as good as netconvert can be, and it depends on the input file.
1) is not an error, SAGA is telling you that it cannot generate trips because the network is bad.
2) see above. the parking are extracted from OSM, if they are not enough, you have to manually add them and fix the capacity.
3) I worked on this over the weekend and you'll have a fixing commit as soon as I finish the tests.

**Comment by lcodeca** [comment]
I fixed the TAZ so now it works without the --single-taz option.

**Comment by Shiyunyang-seu** [comment]
Thanks!

**Comment by Shiyunyang-seu** [comment]
Hi, so sorry to reopen this question, I used the updated file, but a new error occurs. I can not figure out what the problem is.
![error](https://user-images.githubusercontent.com/55737075/79770727-5edf1a00-8360-11ea-8cd5-827e5ebdcc0a.png)

**Comment by lcodeca** [comment]
What the error is saying that in the file osm_taz.xml there is an invalid token (line 3, column 29).
Have you changed the file yourself? What's in that line?
I don't know what's going on without seeing the files.
Additionally, would you mind opening a new issue when you have a new problem?
