### ISSUE TITLE
The error in taz.xml

### ISSUE THREAD

**Issue by Shiyunyang-seu** [lcodeca/SUMOActivityGen#6]
Hi, I used the scenarioFromOSM.py, and do not change the osm_taz.xml file, but an inexplicable error has occurred. 
[osm_taz.zip](https://github.com/lcodeca/SUMOActivityGen/files/4504915/osm_taz.zip)

**Comment by lcodeca** [comment]
It's an encoding problem. The characters "Ë«ËþœÖµÀ" are not recognized by your `xml.etree.ElementTree` library. 
I tested it before with the OSM file you provided in https://github.com/lcodeca/SUMOActivityGen/issues/4#issue-602903649 and it works fine for me.
I'm using Linux (Debian Stable) and I don't have a windows machine to test it.

**Comment by Shiyunyang-seu** [comment]
Thanks for your reply.The problem is that xml.etree.ElementTree can't recognize Chinese characters. I tried to correct the error, but it didn't seem to work.
![encoding](https://user-images.githubusercontent.com/55737075/79784364-b4bdbd00-8374-11ea-9581-903672b287f1.png)

**Comment by lcodeca** [comment]
If you check your OSM file, the first line is `<?xml version='1.0' encoding='UTF-8'?>` from standard.
As you can see, it's exactly the encoding I use in my scripts (lines 305,306). For this reason, I can process your file without any issues.
You need to see how Anaconda and xml.etree.ElementTree are installed in your windows machine and if you have encoding issues there.
