### ISSUE TITLE
Subway travel is ignored in Activitygen

### ISSUE THREAD

**Issue by Shiyunyang-seu** [lcodeca/SUMOActivityGen#7]
Hi, when using Activitygen to generate activity-based travel, I found that passengers chose public transport but did not consider taking subway (the subway station has been established successfully and also the access lanes are available).

**Comment by lcodeca** [comment]
The public transport trip is generated using [traci.simulation.findIntermodalRoute](https://github.com/lcodeca/SUMOActivityGen/blob/master/activitygen.py#L569). 
Are you sure that the definition of the subway generated by netconvert works? 
Have you changed it by hand? 
If so, have you re-generated the public transportation routes? 
In SAGA is done running [ptlines2flows.py](https://github.com/lcodeca/SUMOActivityGen/blob/master/scenarioFromOSM.py#L344) from the SUMO tools.
