### ISSUE TITLE
How to make activitygen create a continuous multi day travel plan (differentiate between weekday and weekend)

### ISSUE THREAD

**Issue by Shiyunyang-seu** [lcodeca/SUMOActivityGen#9]
Hi, how can I simulate a continuous multi day travel plan by activitygen? And make it conform to the characteristics of morning and evening peak travel and more weekend entertainment activities than the weekday.

**Comment by lcodeca** [comment]
SAGA follows blindly the configuration file ([see activitygen.json](https://github.com/lcodeca/SUMOActivityGen/blob/master/defaults/activitygen.json))
You need to define different activities for the different weekdays ([see "activities"](https://github.com/lcodeca/SUMOActivityGen/blob/master/defaults/activitygen.json#L31)) and compose the proper activity chains for the slices of mobility ([see "slices"](https://github.com/lcodeca/SUMOActivityGen/blob/master/defaults/activitygen.json#L85)).

**Comment by Shiyunyang-seu** [comment]
Thanks!
